name: No submodule update checker

on:
  pull_request:
    paths:
      - 'RobustToolbox'

jobs:
  this_aint_right:
    if: github.actor != 'sleepyyapril' && github.actor != 'VMSolidus' && github.actor != 'DEATHB4DEFEAT'
    name: Submodule update in pr found
    runs-on: VK-Cloud
    steps:
      - name: Fail
        run: exit 1
